### ISSUE TITLE
[Data Request]: Grassland Status Dataset

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#10]
### ID

grassland_status

### Description

The HRL Grassland 2018 Raster product provides a basic land cover classification with 2 thematic classes (grassland / non-grassland) at 10m spatial resolution and will cover the pan-European area of EEA39. 

### Target Platform

Rasdaman

### Preferred Method

Assisted by the platform provider

### Axes

Lat, Long: horizontal extent - Europe;
regular, resolution: 10m, uom: metre

T: time, axis inserted to create time series database;
Time slice - "2018-01-01T20:12:02”;
lower bound same as upper bound

### Cell type

8 bit integer, with 3 significant values-
0 - All non-grassland areas
1 - Grassland
255 - Outside Area

### Null values

255 - Outside Area

### (Meta) data Standards

standards data complies with Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services, Date of publication: 2010-12-08

### APIs

OGC WMS, WCS, WCPS

### Access control

login-protected, access only for FAIRiCUBE beneficiaries

### Responsible

Constructor University, mbasak@constructor.university

### Data Source

Origin of data – EEA, URL -- https://land.copernicus.eu/pan-european/high-resolution-layers/grassland/status-maps/grassland-2018?tab=download

### Data Preprocessing

None in particular

### Quality Control

Quality assurance followed the ISO9001 standards for Quality Management and the INSPIRE data quality elements

### Documents & publications

None

### License

License Link - https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32013R1159

### Ownership

EEA

### Personal Data

No personal data are captured in this datacube

**Comment by Mohinem** [comment]
Import done

**Comment by Mohinem** [comment]
Reimported with original CRS.

**Comment by KathiSchleidt** [comment]
same as #26
