### ISSUE TITLE
[Data Request]: european_settlement_map

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#15]
### ID

european_settlement_map

### Description

Time series data mapping human settlements in Europe

### Target Platform

Rasdaman

### Preferred Method

Assisted by the platform provider

### Axes

* Lat, Long: horizontal extent - Europe; regular, resolution: 10m, uom: metre
* T: time, axis inserted to create time series database; Time slice - "2018-01-01T20:12:02”; lower bound same as upper bound

### Cell type

Integer denoting whether the pixel dnotes land, water, or residential/non-residential built up area

### Null values

0 – No Data

### (Meta) data Standards

standards data complies with Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services, Date of publication: 2010-12-08

### APIs

OGC WMS, WCS, WCPS

### Access control

login-protected, access only for FAIRiCUBE beneficiaries

### Responsible

Jacobs/Constructor University, mbasak@jacobs-university.de

### Data Source

EEA, URL - https://land.copernicus.eu/pan-european/GHSL/european-settlement-map/esm-2015-release-2019?tab=download

### Data Preprocessing

None

### Quality Control

Validation was performed according to the following report- https://land.copernicus.eu/user-corner/technical-library/the-european-settlement-map-validation-report

### Documents & publications

None

### License

Validation was performed according to the following report- https://land.copernicus.eu/user-corner/technical-library/the-european-settlement-map-validation-report

### Ownership

EEA

### Personal Data

None

**Comment by Mohinem** [comment]
Time to import with original CRS

**Comment by Mohinem** [comment]
Reimported

**Comment by KathiSchleidt** [comment]
same as #35
