### ISSUE TITLE
Dataset Identifier and connection to Dataset Metadata

### ISSUE THREAD

**Issue by KathiSchleidt** [FAIRiCUBE/data-requests#19]
### ID

[Not a Data Request]: Dataset Identifier and connection to Dataset Metadata

### Description

I'm trying to understand how we get from [data requests](https://github.com/FAIRiCUBE/data-requests/issues?q=) to dataset metadata records. My understanding is that the content of the data request form will be extracted and provided to the [catalog](https://catalog.fairicube.eu/), what's progress on this?

In addition, I'd expect information on the location of the successfully ingested dataset at the end of the request issue. At present, we have to guess which layer on rasdaman corresponds to which data request. On EOX, I still don't understand how we can share datasets, what should be provided so users can access this dataset.

I'd like suggestions on how we progress here

**Comment by Schpidi** [comment]
adding in @eox-cs1 to the discussion

**Comment by KathiSchleidt** [comment]
As we will be providing a link from the rasdaman coverage datasets to the corresponding metadata record, it would be essential that the coverage ID and metadata record names are aligned. 

Example: for the Corine Land Cover Dataset, the Coverage ID is "corine_land_cover". Thus, the corresponding metadata record should be https://catalog.fairicube.eu/stac/corine_land_cover.json

**Comment by KathiSchleidt** [comment]
@pebau when we discussed providing the link of the STAC metadata record within the coverage metadata, you requested a valid [XML example](https://github.com/FAIRiCUBE/data-requests/blob/main/encoding-examples/dominant_leaf_type-metadata.xml), now provided. For some reason, rasdaman seems to have problems with this encoding, the Coverage from which this DescribeCoverage example stems is no longer accessible since @Mohinem tried to extend it.

**Comment by pebau** [comment]
ok, we look at it internally + come back.

**Comment by KathiSchleidt** [comment]
@pebau please see dominant_leaf_type for what has been going wrong, not accessible since @Mohinem tried to add metadata

**Comment by Mohinem** [comment]
Hi everyone, some update.

1. I have imported a new coverage called dominant_leaf_type_2018, following suggestions of https://github.com/FAIRiCUBE/data-requests/issues/52#issuecomment-1684052202. 

2. I have a demo dataset with metadata added, called dominant_leaf_type_2018_demo. Please see the metadata and confirm if that's fine (or suggest changes).

**Comment by pebau** [comment]
just to avoid misunderstandings: there is no fixed rasdaman schema for coverage metadata, it is  "any" as per coverage definition. The ingester can provide "any"thing, and if it happens to be a color table, then the color table gets delivered. 

Any details, descriptions of metadata items etc are supposed to go into the catalog (searchable, curated) ...or into coverage metadata (not searchable, uncurated).

**Comment by KathiSchleidt** [comment]
@pebau in that case, I'm assuming that a slightly more professional encoding in line with OGC best practices would be valid?

I wanted the schema to make sure I'm doing everything correctly, experience has shown that rasdaman doesn't respect schemas. My initial proposal of providing a dedicated metadata element as follows seems not supported by rasdaman:
`<gmlcov:metadata xlink:href="https://catalog.fairicube.eu/stac/dominant_leaf_type.json"/>`

Going back to @Mohinem proposal
```
<gmlcov:metadata>
	<gmlcov:Extension>
		<rasdaman:covMetadata>
			<AREA_OR_POINT>Area</AREA_OR_POINT>
			<role>https://codelists.fairicube.eu/metadata/MetadataCatalogLink</role>
			<title>Dominant Leave Type metadata on the FAIRiCUBE Catalog</title>
			<href>https://catalog.fairicube.eu/stac/dominant_leaf_type.json</href>
			<DataType>Thematic</DataType>
			<colorPaletteTable>{'colorTables': [...]}</colorPaletteTable>
		</rasdaman:covMetadata>
	</gmlcov:Extension>
</gmlcov:metadata>
```
What bothers me is:
- use of the HAL components as elements, not attributes
- providing role, title and href at this level implies that the other attributes all conform to the role MetadataCatalogLink

How about we group role, title and href into a `Link` element using xlink as follows:
```
<gmlcov:metadata>
	<gmlcov:Extension>
		<rasdaman:covMetadata>
			<AREA_OR_POINT>Area</AREA_OR_POINT>
			<Link xlink:role="https://codelists.fairicube.eu/metadata/MetadataCatalogLink"
xlink:title= "Dominant Leaf Type metadata on the FAIRiCUBE Catalog" xlink:href="https://catalog.fairicube.eu/stac/dominant_leaf_type.json" />
			<DataType>Thematic</DataType>
			<colorPaletteTable>{'colorTables': [...]}</colorPaletteTable>
		</rasdaman:covMetadata>
	</gmlcov:Extension>
</gmlcov:metadata>
```

**Comment by KathiSchleidt** [comment]
Clarified in [Metadata for datacubes #21](https://github.com/FAIRiCUBE/FAIRiCUBE-Hub-issue-tracker/issues/21)

Structure:
```
<gmlcov:metadata>
	<gmlcov:Extension>
		<rasdaman:covMetadata>
			<fic-md:fairicubeMetadata 
				xlink:role="https://codelists.fairicube.eu/metadata/MetadataCatalogLink" 
				xlink:title="Dominant Leave Type metadata on the FAIRiCUBE Catalog" 
				xlink:href="https://catalog.fairicube.eu/stac/dominant_leaf_type.json"/>
		</rasdaman:covMetadata>
	</gmlcov:Extension>
</gmlcov:metadata>
```

[XSD Schema](https://github.com/FAIRiCUBE/data-requests/blob/main/CoverageSchemas/MD-LinkSchema.xsd)

[Full Example](https://github.com/FAIRiCUBE/data-requests/blob/main/encoding-examples/dominant_leaf_type-metadata.xml)
