### ISSUE TITLE
Crop Parcel Registration (BRP)

### ISSUE THREAD

**Issue by robknapen** [FAIRiCUBE/data-requests#20]

**Comment by Mohinem** [comment]
After some googling, I found the relevant website -

https://www.wur.nl/en/project/image_spectral_radiometry_assessment_for_lpis_applications.htm

Please help me obtaining access to the data.

**Comment by robknapen** [comment]
I don’t think that is a correct source.

@vittekm should be able to provide the BRP datasets for multiple years. We should have those internally at WEnR. Originally these are vector data, so need to be rasterised (at 5m or 10m) and only the open data part kept. Also for each year there is an associated list of crop codes, with slight variations across years.

In the vector data the parcel geometries have both a crop code and a crop name attribute, but when rasterised the crop name is lost so the crop code to crop name mapping needs to be saved somewhere (as metadata?).

**Comment by KathiSchleidt** [comment]
@Mohinem why are you not utilizing the data from the source originally specified: https://www.pdok.nl/introductie/-/article/basisregistratie-gewaspercelen-brp-

While the original dataset is vector, I see there's also a WMS - could one utilize this to obtain a raster representation?

As for the alternative source you suggest, this seems to be based on somebody's dissertation, not that trustworthy, while PDOK is a governmental institution

**Comment by pebau** [comment]
I see that some facets still need to be clarified prior to ingestio. Closing for now, feel free to [open a new data request with all information provided](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data).
