### ISSUE TITLE
[Data Request]: 

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#21]
### ID

dominant_leaf_type

### Description

Timeseries denoting the dominant leaf type of trees over the EEA-39 region.

### Target Platform

Rasdaman

### Preferred Method

Assisted by the platform provider

### Axes

Lat, Long: horizontal extent - Europe; regular, resolution: 10m, uom: metre
T: time, axis inserted to create time series database; Time slice - "2018-01-01T20:12:02”; lower bound same as upper bound

### Cell type

Integer with the following values -
0 - All non-tree covered areas
1 - Broadleaved trees
2 -  Coniferous trees
255 - Outside area

### Null values

255 - Outside Area

### (Meta) data Standards

standards data complies with Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services, Date of publication: 2010-12-08

### APIs

OGC WMS, WCS, WCPS

### Access control

login-protected, access only for FAIRiCUBE beneficiaries

### Data Source

EEA, URL - https://land.copernicus.eu/pan-european/high-resolution-layers/forests/dominant-leaf-type/status-maps/dominant-leaf-type-2018?tab=download

### Data Preprocessing

None in particular

### Ownership

EEA

**Comment by Mohinem** [comment]
Imported in correct CRS

**Comment by KathiSchleidt** [comment]
same as #29
