### ISSUE TITLE
[Data Request]: Grassland change

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#23]
### ID

grassland__change

### Description

Data representing the change in grassland area (verified/unverified gain or loss of grassland) in the EEA 39 area.

### Axes

Lat, Long: horizontal extent - Europe;
regular, resolution: 10m, uom: metre

T: time, axis inserted to create time series database;
Time slice - "2018-01-01T20:12:02”;
lower bound same as upper bound

### Cell type

8 bit integer, with the following significant values -

0: All non-grassland areas
1: Grassland gain
2: Grassland loss
10: Unchanged grassland in both years
11: Unverified grassland gain
22: Unverified grassland loss
254: Unclassifiable in any of parent status layers
255: Outside area

### Null values

255 -  outside area

### (Meta) data Standards

standards data complies with Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services, Date of publication: 2010-12-08

### APIs

OGC WMS, WCS, WCPS

### Access control

login-protected, access only for FAIRiCUBE beneficiaries

### Responsible

Constructor University, mbasak@constructor.university

### Data Source

Origin of data – EEA, URL -- https://land.copernicus.eu/pan-european/high-resolution-layers/grassland/change-maps/grassland-change-2015-2018

### Data Preprocessing

None in particular

### Quality Control

Quality assurance followed the ISO9001 standards for Quality Management and the INSPIRE data quality elements

### Documents & publications

None

### License

License Link - https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32013R1159

### Ownership

EEA

### Personal Data

No personal data are captured in this datacube

**Comment by Mohinem** [comment]
Already imported in right crs.

**Comment by KathiSchleidt** [comment]
Could we please delete the defective grassland_change layer?

**Comment by pebau** [comment]
all done, so closing. BTW, thanks for providing all information nicely in the request! That has made all much smoother.
