### ISSUE TITLE
[Data Request]: Corine Land Cover

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#24]
### ID

corine_land_cover

### Description

Timeseries about types of land area in the EEA-39 regions and overseas French territories.

### Target Platform

Rasdaman

### Preferred Method

Assisted by the platform provider

### Axes

Lat, Long: horizontal extent - EEA39 + French DOMs (overseas territories);
regular, resolution: 100m, uom: metre

T: time, axis inserted to create time series database;
Time slice - "2018-01-01T20:12:02”;
lower bound same as upper bound

### Cell type

Signed byte type - denoting different land types

### Null values

-128 - NoData Value

### (Meta) data Standards

standards data complies with Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services, Date of publication: 2010-12-08

### APIs

OGC, WMS, WCS, WCPS

### Access control

login-protected, access only for FAIRiCUBE beneficiaries

### Responsible

Constructor University, mbasak@constructor.university

### Data Source

Origin of data – EEA, URL -- https://land.copernicus.eu/pan-european/corine-land-cover

### Data Preprocessing

None

### Quality Control

Quality assurance followed the ISO9001 standards for Quality Management and the INSPIRE data quality elements

### Documents & publications

None

### License

http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32013R1159

### Ownership

EEA

### Personal Data

No personal data are captured in this datacube

**Comment by KathiSchleidt** [comment]
@Mohinem what's the difference between this request and #30 ? My assumption is that you created this before the content of the inventory.xlsx was transferred to Git.

However, there are some divergences between what you've entered here, and what I see in #30, e.g. under #30 under Time Coverage, we see: 1990 2000 2006 2012 2018, while here you've reduced it to Time slice - "2018-01-01T20:12:02”;

Could you please clarify?

**Comment by KathiSchleidt** [comment]
@Mohinem I've noticed a lot of activity on this dataset. In the most recent version, you now provide data at 10m resolution for all years. What would interest me is the source of this higher-resolution data, as the original source seems to be at 100m

**Comment by Mohinem** [comment]
@KathiSchleidt that seems to be a mistake, I have created a new coverage with 100m resolution, please check.

**Comment by KathiSchleidt** [comment]
Thank you for correcting to the correct resolution.

Question - why do we have 6 IDs listed in the Inventory (on e general, one per year), but only one in rasdaman?

**Comment by pebau** [comment]
so the dataset is there, hence closing.
