### ISSUE TITLE
WebGUI submit button not working when updating a record

### ISSUE THREAD

**Issue by mari-s4e** [FAIRiCUBE/data-requests#275]
I have tried multiple times to update this data-request record https://github.com/FAIRiCUBE/data-requests/pull/272 through the WebGUI, but when I click the submit button nothing happens, the data-request does not get updated. And when I click on the back button all the new information gets lost.

**Comment by baloola** [comment]
Hi there @mari-s4e. Apparently there is an issue with the backend, I will work on it and will let you know once it's fixed.

**Comment by baloola** [comment]
@mari-s4e There was a recent issue with the backend component for data requests. This should be resolved now. Could you please try editing your data request record again and confirm if everything is working as expected?

**Comment by baloola** [comment]
I think this issue was resolved

**Comment by mari-s4e** [comment]
Hi Mussab, I have tried today to use the editor, but I just have a blank screen and 500 errors. Can you share when the editor will be working again? Thanks.

**Comment by mari-s4e** [comment]
Hi Mussab, yes now it is working again :)

**Comment by mari-s4e** [comment]
Unfortunately I have to reopen the issue, I am having the same problem with the submit button. Nothing happens :(

**Comment by baloola** [comment]
There is a new backend release now, could try it  again, 
Thanks

**Comment by mari-s4e** [comment]
Hi Mussab, YES! I was finally able to update the record. It took 5 iterations (today only) because many mandatory fields were not indicated as such in the GUI.

**Comment by KathiSchleidt** [comment]
@mari-s4e @baloola I've now created an issue [Indicate Mandatory Fields in WebGUI](https://github.com/FAIRiCUBE/catalog/issues/27)
