### ISSUE TITLE
Corine Land Cover 

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#30]

**Comment by robknapen** [comment]
Hi, I was looking at this dataset in rasdaman, and am now a bit curious about how we handle the temporal dimension in the data (it might already be according to a standard now). This is WCS Envelope data returned:

```
"gml:Envelope": {
          "@srsName": "http://localhost:8080/rasdaman/def/crs-compound?1=http://localhost:8080/rasdaman/def/crs/OGC/0/AnsiDate&2=http://localhost:8080/rasdaman/def/crs/EPSG/0/3035",
          "@axisLabels": "ansi Y X",
          "@uomLabels": "d metre metre",
          "@srsDimension": "3",
          "gml:lowerCorner": "\"2018-01-01T08:12:02.000Z\" 900000 900000",
          "gml:upperCorner": "\"2018-01-02T08:12:02.000Z\" 5500000 7400000"
        }
```

Is it custom to label the temporal axis as 'ansi' (guess this is short for ansiDate)? And to give the dataset from 2018 only a 1 day temporal range?

**Comment by Mohinem** [comment]
In both cases, I started the custom. There is no logic for the naming of the temporal axis, it's just that I never changed it.
And as for the temporal range, the choice of the year was fixed, as I was importing the 2018 dataset. The choice of date and time is arbitrary.

**Comment by robknapen** [comment]
@KathiSchleidt Maybe we need some best practices / guidelines for this then?

**Comment by robknapen** [comment]
@Mohinem The reported bounding box for this dataset also looks incorrect, it is an European dataset.

Might be good to match the metadata with:  https://land.copernicus.eu/pan-european/corine-land-cover/clc2018?tab=metadata ?

![Screenshot 2023-06-22 at 11 55 58](https://github.com/FAIRiCUBE/data-requests/assets/1943289/51ac8fb8-3749-4e5a-8e31-998c4a325d21)

**Comment by KathiSchleidt** [comment]
Hi Both,

On the name for the time dimension, I agree that `ansi` is not really suitable (think this comes from ancient history, nobody ever bothered to change). I'd hoped that @pebau would provide guidance as our Master of Coverages, but in lieu of that, lets define that the date should simply be called `date`

On the bbox issue you see in the rasdaman GUI, this is a mix of strange projections and poor portrayal, I got the same effect in QGIS when I played with 3035 vs 4326 bboxes. When I do a simple bbox with just the 4 corners and project to Lambert, I got the following (Blue is the true extent of the LAEA data, Red is the surrounding WGS84 bbox):

![CopernicusBBwWGS84BBox_LAEA](https://github.com/FAIRiCUBE/data-requests/assets/11915304/c8fa1288-290c-4076-a65d-f83e879dc8a9)

However, when I added additional points along the top and bottom edges of the bbox, it became far saner:

![LAEA-WGS84](https://github.com/FAIRiCUBE/data-requests/assets/11915304/c0f2c81b-ee24-4910-833e-89bd314fba44)

@pebau might be worthwhile refining the portrayal in the GUI as this is bound to confuse people

**Comment by pebau** [comment]
the data obviously are available, discussion of yearly timeslice handling as concluded, what remains above is a visualization issue not part of data-request. So closing.
