### ISSUE TITLE
Clarify Process utilizing the Project for Ingestion Requests

### ISSUE THREAD

**Issue by KathiSchleidt** [FAIRiCUBE/data-requests#33]
@Schpidi @StefanBrand there are issues when utilizing the Project for Ingestion Requests, the content is not correctly transferred to the created issue. Details at #31 

Could you please clarify these details, also provide a description of how this process should be used. I much like the functionality, but without a description, things are falling apart

**Comment by KathiSchleidt** [comment]
@Mohinem I notice that when you've made a dataset available via rasdaman, you immediately set the status to "Verified by UC"

The way I understand the different status levels, I'd expect:
- Requested: all the requests you haven't gotten to yet
- Provisioning: you're working on it
- Access Details given: you've finished work, dataset is available for UC to check
- Verified by UC: this should be done by the UC partners, once they've accessed and validated the dataset

**Comment by Mohinem** [comment]
Looks good.

**Comment by KathiSchleidt** [comment]
We may want to clean a bit, as we have duplicate issues for the various datasets you'd started without utilizing this project approach. I did my best to make sure we have the relevant links between them.

I've also just sent out a mail to the WP2 list warning UC partners that they'll be contacted for validating their requested datasets

**Comment by baloola** [comment]
- The solution should extract the needed info regardless of the approach. What is needed is some standerdised values for the axes in the created issues.
- regarding the yaml generator, there were some old local changes that were not pushed, sorry if it caused any confusion. The approach is to directly generate STAC items as you mentioned.

**Comment by KathiSchleidt** [comment]
@baloola when will the STAC items be generated? Can this be triggered by those doing the data ingestion, or is this run as a batch job, or...?

**Comment by baloola** [comment]
Hi @KathiSchleidt, currently the ingestion pipeline is triggered manually. ( it is done now).
And yes in principle we can agree on certain protocols to trigger it by the data ingestion implementers themselves.

**Comment by KathiSchleidt** [comment]
@baloola having a possibility for those ingesting the data to trigger the metadata creation process is just what we need! Please keep up posted on this!

Also - we'd like to provide a link from the rasdaman Coverages to the corresponding STAC metadata record (provide the URL of that record). Our working assumption is that the ID provided in the data request form will also become the identifier of the metadata record. Questions to you:
- Is this assumption correct? We can automatically generate the URL of the metadata record by prepending a catalog URL to the ID? 
- I'm a bit worried about the parallel data request issue structures, with new data requests utilizing the form provided when creating a new issue, the old ones having the information somehow packed in the "project" bit on the right. Will the information from both sources be imported? What do you plan on doing if there's a clash (e.g. #50, not sure if there's a clash, but there's information in both places)

**Comment by KathiSchleidt** [comment]
Clarified at meeting 2023_08_08 : Data Ingestion vs. Dataset Metadata, MoM in FAIRiBOOK under meetings_MoM
