### ISSUE TITLE
[Data Request]: Climate Data - Rainfall flux

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#42]
### ID
rainfall_flux

### Description
Variable - Rainfall flux , for the Copernicus climate dataset (https://cds.climate.copernicus.eu/cdsapp#!/dataset/derived-near-surface-meteorological-variables?tab=overview)

**Comment by pebau** [comment]
insufficient information for ingestion, so closing. Feel free to file a [complete request](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data).
