### ISSUE TITLE
Handling irregular series

### ISSUE THREAD

**Issue by KathiSchleidt** [FAIRiCUBE/data-requests#44]
In many of the Copernicus datasets, we're achieving ever higher resolution. The downside of this advance is that it's hard to provide all the data within one Coverage. How do we deal with such datasets? I see the following 2 options:
- provide them as separate Coverages (so one for all the years with 20m resolution, 2nd for the years with 10m resolution)
- we resample the 20m to 10m (or vice versa)

Thoughts?

**Comment by KathiSchleidt** [comment]
Same issues apply to irregular time series

**Comment by pebau** [comment]
> Same issues apply to irregular time series

different story - irregular timeseries can handle non-regular timesteps without any modification, they are made for that. So no problem. Actually, we do that always with Copernicus as it turns out they are not as regular as one might wish.

**Comment by pebau** [comment]
> > Same issues apply to irregular time series
> 
> different story - irregular timeseries can handle non-regular timesteps without any modification, they are made for that. So no problem. Actually, we do that always with Copernicus as it turns out they are not as regular as one might wish.

...and this is why it should be indicated in the data request, then axes get defined accordingly.

**Comment by pebau** [comment]
> In many of the Copernicus datasets, we're achieving ever higher resolution. The downside of this advance is that it's hard to provide all the data within one Coverage. How do we deal with such datasets? I see the following 2 options:
> 
>     * provide them as separate Coverages (so one for all the years with 20m resolution, 2nd for the years with 10m resolution)

I have not seen this, can you give me an example? Sentinel data we know offer in places 10m AND 20m, but not varying.

**Comment by KathiSchleidt** [comment]
On the spatial variance, not within one year's data, but if we see these as a time-series (value every 3 years), the older values (including 2015) are on a 20m grid, the newer ones (as of 2028) on 10m (this is consistent across all Copernicus datasets due to the underlying increase in Sentinel resolution, example https://land.copernicus.eu/pan-european/high-resolution-layers/forests/dominant-leaf-type/status-maps/dominant-leaf-type-2018?tab=metadata)

The question remains how we deal with this:
- create multiple coverages, one per spatial resolution
- create one coverage and resample to the higher resolution

**Comment by pebau** [comment]
Update: we can build virtual coverages uniting different resolutions. The server will automatically adjust to the requested resolution, where necessary, upon retrieval.

**Comment by KathiSchleidt** [comment]
@pebau what's the resampling algorithm applied? As we saw in Manuel's presentation on resampling, very different algorithms are required based on the nature of the underlying data!

I WOULD much appreciate such an automatic resampling option, but it has to be done right!

**Comment by pebau** [comment]
@KathiSchleidt I understand your concern but, unfortunately, currently this cannot be controlled externally.

**Comment by KathiSchleidt** [comment]
@pebau my concern goes way deaper, as I have yet to understand where within the Coverage encoding such information can be stored. I'm assuming that the automatic resampling utilizes linear interpolation, applicable to very few of the datasets we're dealing with.

Maybe topic for some well-deserved beers at IGARSS this week?

**Comment by pebau** [comment]
@KathiSchleidt  see cis 1.1, coverages.xsd:

    <complexType name="InterpolationRestrictionType">
        <sequence>
            <element name="AllowedInterpolation" type="anyURI" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

...where OGC is responsible for providing the URIs for the interpolation types. AFAIK this has to come from the sensor folks - what do they offer?

**Comment by pebau** [comment]
@KathiSchleidt also, irregular and interpolation are two different topics - can we maybe factor out interpolation? If so, what remains to be clarified about irregular timeseries?

**Comment by KathiSchleidt** [comment]
@pebau 
`Question: why do we need data older than 2018?`: 
because topics such as climate change deal with change over time, not just the current snapshot!

`Update: we can build virtual coverages uniting different resolutions. The server will automatically adjust to the requested resolution, where necessary, upon retrieval.`;
This is where the interpolation topic got confounded in.

`...where OGC is responsible for providing the URIs for the interpolation types. AFAIK this has to come from the sensor folks - what do they offer?`
2 answers:
- the "sensor folks" in OGC do exactly what they want/need, no regard as to external issues
- I'm not aware of a request for such structures, assuming the coverage group has a clean list of types they'd need provided?

`factor out interpolation?`: 
Please do!

**Comment by robknapen** [comment]
My interpretation (from a UC perspective) of the ‘irregular series’ in the title is ‘time series data that is not harmonised’. So while it is a series, the data at each time step available might have some different characteristics. I.e. in spatial resolution, or in classification.

For use in data processing / ML it would need to be harmonised first (I would refer to that as pre-processing). For me, after such pre-processing (and probably some other operations) it would become an analysis ready dataset (ARD). When part of those steps can happen automatically in the background (in a sensible way), even better :-)

If we store and document such ARDs, they might save future data scientists some work.

**Comment by KathiSchleidt** [comment]
@robknapen from your UC perspective, what would you prefer:
- 2 separate Coverages, split by spatial resolution (10 & 20m)
- 1 'harmonized' Coverage, with the resolution taken down to 20m

I'm aware that the ideal solution would be 1 'harmonized' Coverage, with the resolution of the old data refined to 10m, but such processing is out-of-scope for FAIRiCUBE

Also, looks like the NHM Occurrence Cube UC will be focusing on 100m resolution

**Comment by robknapen** [comment]
@KathiSchleidt In that case I don’t think we have another option than ask to keep the coverages separate, and do the pre-processing as needed as part of our use case work. We might very well need the 10m data when it concerns agricultural aspects of our UC.

**Comment by KathiSchleidt** [comment]
I pulled the interpolation topic to #58

**Comment by pebau** [comment]
closing this after migration of the topic

**Comment by pebau** [comment]
trying again...

**Comment by pebau** [comment]
giving up with github today - time slot used up.

**Comment by pebau** [comment]
@robknapen 
> My interpretation (from a UC perspective) of the ‘irregular series’ in the title is ‘time series data that is not harmonised’. So while it is a series, the data at each time step available might have some different characteristics. I.e. in spatial resolution, or in classification.

The good news is that the term "irregular axis" as in the standard contains already harmonization of key coverage aspects. 
So no difference in classification etc. The only difference to regular axes is that coordinates do not have to be at regular distances, ie: there is no single resolution any longer. Rasdaman can handle that, and it is common in our world.

**Comment by KathiSchleidt** [comment]
@pebau when closing an issue, it is good practice to provide a summary of the conclusions reached. What do you propose? Original issue text here:

```
In many of the Copernicus datasets, we're achieving ever higher resolution. The downside of this advance is that it's hard to provide all the data within one Coverage. How do we deal with such datasets? I see the following 2 options:

* provide them as separate Coverages (so one for all the years with 20m resolution, 2nd for the years with 10m resolution)
* we resample the 20m to 10m (or vice versa)
```

I have no idea what your text on "irregular axis" pertains to in this context, free association?

**Comment by KathiSchleidt** [comment]
Based on the feedback from @robknapen we go for the first option proposed:
- provide them as separate Coverages (so one for all the years with 20m resolution, 2nd for the years with 10m resolution)

For Copernicus data, this means one coverage for data until 2015, a second for data as of 2018.
Closing this issue
