### ISSUE TITLE
[Data Request]: Climate Data - Snowfall flux

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#45]
### ID
snowfall_flux

### Description
Variable - Snowfall flux, from the Copernicus climate dataset

**Comment by pebau** [comment]
cannot process as is, as insufficient data are provided. Closing for now, please feel free to create new issue coherent with the [standard procedure](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data).
