### ISSUE TITLE
[Data Request]: Climate Data - Surface air pressure

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#46]
### ID
surface_air_pressure

### Description
Variable - Surface Air Pressure, from the Copernicus climate dataset

**Comment by pebau** [comment]
insufficient data provided, so closing. Feel free to create a new issue coherent to the [standard procedure](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data).
