### ISSUE TITLE
[Data Request]: Climate Data - Surface downwelling longwave radiation

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#47]
### ID
surface_downwelling_longwave_radiation

### Description
Variable - Surface downwelling longwave radiation, from the Copernicus climate dataset.

**Comment by pebau** [comment]
insufficient data provided, so closing. Feel free to file a [complete data request](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data).
