### ISSUE TITLE
[Data Request]: Climate Data - Surface downwelling shortwave Radiation

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#48]
### ID
surface_downwelling_shortwave_radiation

### Description
Variable - Surface downwelling shortwave Radiation , as part of the Copernicus Climate Dataset

**Comment by pebau** [comment]
insufficient data provided, so closing. Feel free to file a [complete data request](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data).
