### ISSUE TITLE
enhanced issue template inputs (proposal)

### ISSUE THREAD

**Issue by baloola** [FAIRiCUBE/data-requests#49]
For the sake of a stable stac generation pipeline, it would make sense to standardize the input strings in the created issues (especially dimensions & variables).
I have edited the issue template to synchronize the dimensions inputs with the stac generator code.
The proposed new template structure is as seen here:

![Screenshot from 2023-07-05 10-14-43](https://github.com/FAIRiCUBE/data-requests/assets/28819736/c59588c8-d95a-4ba3-af68-2ba5d7f2486b)

as for the excel sheet I would propose to insert an `[extent](spatial reference)` as the `coverage` field, and to use " `start date(ISO)-end date(ISO)` " for the `time coverage` and a " `number unit` " for the time resolution.

for example  : 
Coverage =>  [-180.0, -90.0, 180.0, 90.0] (EPSG:4326)
Time Coverage => 1990-01-01T00:00:00Z/2023-01-01T00:00:00Z
Time Resolution =>  1 year

Any thoughts ?

**Comment by KathiSchleidt** [comment]
Related to  [Dimensional structure for datasets #43](https://github.com/FAIRiCUBE/data-requests/issues/43) and  [Handling irregular series #44](https://github.com/FAIRiCUBE/data-requests/issues/44) 

Also related to discussions on the update of D4.2 dataset metadata, providing explicit STAC elements for each concept (and concepts for each STAC element). Example is the Cell Type description in the last version of D4.2 (1.4), where the only element from STAC:raster:bands that's explicitly addressed is Null values being mapped to STAC:raster:bands:nodata, rest is just lumped

Further thought on temporal dimensions - one concept we've been discussing under the Occurrence Cubes is a separate Month dimension in addition to the Year dimension, as this would allow us to filter out all occurrences for a specific month over all years (e.g. to answer question such as do the daisies flower in April or May?). Thoughts how to foresee this?

**Comment by pebau** [comment]
@KathiSchleidt Can we establish a list of the relevant use cases, ie time queries? Natural language is perfectly fine.

**Comment by pebau** [comment]
@baloola There will be further information, like interpolation allowed, and we will likely learn from the UCs about a few more metadata only in future while going. Also, some of the items suggested above are cryptic for users and countercting the strive for ARD. Altogether, I am hesitant to put the effort on the user by enforcing particular machine-oriented syntax. 

That said, I applaud the strive for an automatic creation of the metadata records. Here is an easier way, avoiding to constrain and reformat the request form: After creation of the datacube/coverage object in rasdaman we can provide all these metadata standard-compliant through a DescribeCoverage request in XML. This can automate creation of the catalog entry and avoid that users have to do 2 steps dealing with 2 different paradigms, which is what we all obviously want.

**Comment by KathiSchleidt** [comment]
@pebau while I like the approach of exposing all relevant metadata via DescribeCoverage, I worry a bit about the timing for setting up this process. I'd really like to investigate adding additional concepts such as valid interpolation to the Coverage Metadata, but this will take time as to my knowledge, there are currently no structures foreseen for such information within the Coverage standards.

In addition, as most of this information is included in the Ingestion Request anyway (it doesn't just magically appear in the DescribeCoverage, it's all taken from the ingestion request and integrated into the Coverage when it's created), I'd prefer for the present to harvest this information directly from the Ingestion Request (at least for the first iteration, so UC partner can finally commence work!)

If we have time left, I'm most happy to explore extracting the necessary metadata from DescribeCoverage, also a nice way of assuring that all information is available directly from the Coverage (once we've set up the necessary structures)

**Comment by KathiSchleidt** [comment]
As the content of this thread is covered in #55, will close here.
