### ISSUE TITLE
supply thumbnail urls

### ISSUE THREAD

**Issue by baloola** [FAIRiCUBE/data-requests#51]
created issues has no associated thumbnail link to them, this results into having  blank items cards in the stac browser ( after ingection)
![Screenshot from 2023-08-02 14-05-52](https://github.com/FAIRiCUBE/data-requests/assets/28819736/591f74ce-6bd5-4a09-96b9-2fda37765709)

**Comment by baloola** [comment]
@pebau I tried to use a `wmts` tile request as a thumbnail `href` and it works fine.
As for using more than one thumbnail, in stac-browser, the card shows only one thumbnail as the card image,
![Screenshot from 2023-08-09 16-14-46](https://github.com/FAIRiCUBE/data-requests/assets/28819736/1cd54704-9c2d-492d-b52c-8a4b1fa71338)


 but in the detaild view below ( when you click on the card) you can view the 2 thumbnail side by side (I used the same url twice)


![Screenshot from 2023-08-09 16-09-52](https://github.com/FAIRiCUBE/data-requests/assets/28819736/ab8b61e5-9d71-47c2-ab86-a2f84819a974)

**Comment by pebau** [comment]
@Mohinem added.

thanks for providing this! First rough idea for automating: use a Wms GetMap with target pixel size and the full extent, as per metadata. This ensures a default. Admins could update the image in the catalog at any time.

WDYT?

**Comment by KathiSchleidt** [comment]
@pebau @baloola Are you now agreed on what information to provide for this thumbnail at what point of the ingestion process? Please document, so we can finalize the ingestion process!!!

**Comment by baloola** [comment]
> @pebau @baloola Are you now agreed on what information to provide for this thumbnail at what point of the ingestion process? Please document, so we can finalize the ingestion process!!!

I think thumbnails will be done as described by @pebau https://github.com/FAIRiCUBE/data-requests/issues/55#issuecomment-1687684592

**Comment by KathiSchleidt** [comment]
Copying the specification from @pebau from #55 to here and closing:

**thumbnail**: if provided, must be a URL pointing to a location accessible by the server; if left empty: stac will create GetMap request of pattern `{service-endpoint}?service=ows&...&layers={layer-name}`
  - image type PNG by convention
  - other optional parameters (crs, style, etc): leave out, take defaults
  - note to implementers: you can always blindly run the expansion, with a user-provided URL it will simply not change anything
  - note to users: can be updated lateron, during final check

Note that I have left out thumbnail2, reason:
- users will have no idea what to put in here -> no information will be provided anyway
- service operator likewise cannot + should not decide about which subregion "looks nice"
