### ISSUE TITLE
Clarifications reruired before I start ingesting multiple year datasets

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#52]
As I will focus more on ingesting datasets of different years from now, there are a few questions.

1. How do I import datasets of different years with different resolutions ? Should I import them as multiple products or as single one ? As of now, I will build virtual coverages with the better resolution, as suggested by @pebau in our email exchanges ?
2. What is the value I should use to represent that the information is a placeholder. Eg. for the year 2018, I had a value "1st January, 20:12:02" to fill the space for the time. However, it doesn't have significance regarding the actual timestamp with the coverage. As of now, there is no way to represent just a year or month information in our systems, and it doesn't make sense to go with the alternatives (like using IndexCRS).

**Comment by robknapen** [comment]
1. As I understand we cannot externally control the interpolation that happens when difference in resolution are automatically resolved, so I guess then they would need to stay separate products. Up to the user then to figure out how to deal with it, based on what is needed for the use case.
2. In case we can only have a full timestamp as placeholder, 1-1-\<year\>:00:00:00 or 1-\<month\>-\<year\>:00:00:00, is as good as any other value I think. Again, it will be up to the user then to interpret it in a sensible way (from available metadata) and write the specific code for handling the data.

**Comment by pebau** [comment]
@robknapen Hi Rob, chiming in here:

ad 1: you can, during ingestion - however, that was not indicated in the data request sheet. 

ad 2: what was the spatial resolution indicated? If nothing is given then resolution is derived from the distance, here: 3 years. Any deviation - such as: valid only in one year - needs to be indicated expressly.

suggestion: what about updating the data request in this light?

**Comment by robknapen** [comment]
@pebau I agree, it seems essential information for the data ingestion so it should be made available in the data requests. With appropriate prompts in the data request form.

**Comment by KathiSchleidt** [comment]
@pebau 
`ad 1: you can, during ingestion - however, that was not indicated in the data request sheet.`:
Data Request Sheet is under the responsibility of WP5. Maybe get in touch with the WP5 lead and discuss this? ;)
In some cases (e.g. elevation data at a very high resolution), interpolation before ingestion may be valuable. 
Open is who can provide guidance as to what interpolation is valid for a dataset. This was the reason for Manuel's presentation on resampling, still working on condensing this information into the soon to be unveiled Knowledge Base. Most thankful for any additional guidance we can get on this topic

`ad 2: what was the spatial resolution indicated? If nothing is given then resolution is derived from the distance, here: 3 years. Any deviation - such as: valid only in one year - needs to be indicated expressly.`
In all data requests I've seen, the years have been cleanly indicated. It may be worth getting in touch with Copernicus responsibles to understand if this 3 (or in the case of Corine Land Cover 6) year cycle is stable or not

On what timestamps to use, I agree with Rob's proposal of `1-1-<year>:00:00:00 or 1-<month>-<year>:00:00:00`
However, what would need to change is the indicated interval, currently set to 1 day (e.g. grassland_status), how can we modify the Envelope & offsetVector to indicate 3 years?

**Comment by KathiSchleidt** [comment]
related to #54. In the context of this post, we should assume that the yearly values are valid for that year (there's no contrary info in the datasets)

ad 1: looks like the current agreement is to keep the spatial resolution of the source dataset, if there are changes in spatial resolution (in all the Copernicus Land datasets between the 2015 and 2018 dataset), we provide 2 coverages

ad 2: if we're dealing with yearly datasets, the month, day, time becomes silly. Ideally we'd be able to drop it, if not, reduce to Jan 1 00:00:00. I still wonder if a dedicated Year CRS wouldn't be valuable here.

**Comment by KathiSchleidt** [comment]
I pulled the interpolation topic to #58

**Comment by pebau** [comment]
we should use Kathi's earlier proposal:
> ad 2: if we're dealing with yearly datasets, the month, day, time becomes silly. Ideally we'd be able to drop it, if not, reduce to Jan 1 00:00:00. 

- trim the incoming date to year boundaries -> set to Jan 01 00:00:00
- set resolution to 1y
- then we will get a slice every 3 years, inbetween there is empty space
- interpolation type "nearest" along time

IMHO this models the outcome of our recent time discussion.

**Comment by KathiSchleidt** [comment]
@pebau is it now possible to set the resolution to 1y after all? This would be great news! Only remaining question is how to deal with the 3-year gaps between values. No-data values for the empty space (e.g. 2016 & 2017)

**Comment by pebau** [comment]
the UC discussion (as well as talks with third parties) have provided valuable insights (oftentimes, new questions) on time handling. While we are digesting this to come up with a concept we will provide an interim solution so that data are available asap. AFAICS later adjustments to more detailed time handling would not affect appearance to users.

**Comment by pebau** [comment]
ditto

**Comment by KathiSchleidt** [comment]
@pebau to `AFAICS later adjustments to more detailed time handling would not affect appearance to users.`
 
At present, in the cases where only one year (of the many years in the source dataset) is being provided, you utilize RectifiedGrid. When you provide multiple points in time (closest we have online is days, near_surface_air_temperature), you switch to ReferenceableGridByVectors 

As these 2 encodings have their differences, I don't see this shift as `not affect appearance to users`

:?

**Comment by KathiSchleidt** [comment]
@Mohinem before closing issues, would you please be so kind as to provide a short summary of the issue resolution?

From what I read in the thread above, while various ideas have been postulated, I have yet to see a proposal for a stable solution that covers all the variants described in my [Inventory-Types](https://nilu365.sharepoint.com/:x:/r/sites/Horizon2021_CUBE/Shared%20Documents/WP2%20-%20use/DataLayerInventory/Inventory_V2-Types.xlsx?d=w937b615a696d45f39be6155fd30619dc&csf=1&web=1&e=Mx1xpa) analysis.

**Comment by Mohinem** [comment]
Alright, based on this conversation, my decision is-

1. Import the datasets as separate products, and leave it to the user to use them as they require.
2. I will put "Jan 01 00:00:00" as the timestamp in the ingredients file which defines the import, till we have more functionality.

I am open to change the decision 1 if required (at the moment), but not decision 2 as this requires something more than what we can offer you right now.

**Comment by KathiSchleidt** [comment]
@Mohinem @pebau I expect that the rational for not creating true cubes will be documented in the next version of D5.2.

**Comment by pebau** [comment]
define "true cube" to the inventors. Maybe just let us proceed now, rather than getting into less productive discussion.

**Comment by KathiSchleidt** [comment]
@pebau 
In a "true cube", I'd expect time as a dimension. I'd gotten that this was the plan based on the fact that all Coverages provided to date have a (unused) time dimension, and the fact that we've been discussing the representativeness of years in various issues.

I was thus surprised to see the Imperviousness dataset now provided as individual Coverages per year.

Please explain what I'm not understanding about cubes!

**Comment by pebau** [comment]
no problem: a cube is a d-dimensional grid where d>0 (sometimes d=0, ie a scalar, is seen as a special case just to achieve uniform treatment). No time axis is required, just as no other specific axis.

There are several reasons why separate objects may be generated, the most prominent one in our project: different resolution at different times. 

Normally, though, we can unite such coverage gangs int a single virtual coverage.

**Comment by KathiSchleidt** [comment]
@pebau That was exactly the logic I was applying, split into separate coverages when the resolution changes, provide together when the resolution is consistent.

This is why I was quite surprised when the Imperviousness dataset was provided as 5 Coverage objects. While I totally understand why the 2018 dataset is provided as a separate coverage, as this dataset has a 10m resolution, what I'm missing is why the other 4 datasets (years 2006, 2009, 2012, 2015, all with 20m resolution) are provided individually. Pertains to the following coverages on the [fairicube rasdaman](https://fairicube.rasdaman.com/rasdaman/ows#/services).

- imperviousness_2006
- imperviousness_2009
- imperviousness_2012
- imperviousness_2015

Please provide clarification as to why these 4 datasets are split, so we can move on in a productive manner

**Comment by pebau** [comment]
following discussion above (and a clarifying, very productive telco) we have found the solution: individual annual layers + an umbrella virtual coverage. This satisfies all the needs expressed. So closing the issue.
