### ISSUE TITLE
[Data Request]: High resolution layer forest type

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#6]
### ID

high_resolution_layer_forest_type

### Description

Time series data depicting forest type and tree cover information across the EEA-39 region 

### Preferred Platform

Rasdaman

### Preferred Method

Assisted by the platform provider

### Axes

    Lat, Long: horizontal extent - Europe; 
    regular, resolution: 10m, uom: metre 
    T: time, axis inserted to create time series database; 
         Time slice - "2018-01-01T20:12:02”; 
         lower bound same as upper bound 

### Cell type

8bit unsigned raster with LZW compression 

### Null values

254 – unclassifiable, 255 – outside area 

### (Meta) data Standards

standards data complies with   Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services,  Date of publication: 2010-12-08 

### APIs

OGC WMS, WCS, WCPS 

### Access control

login-protected, access only for FAIRiCUBE beneficiaries 

### Responsible

Jacobs/Constructor University, mbasak@jacobs-university.de 

### Data Source

Origin of data - EEA
URL - https://land.copernicus.eu/pan-european/high-resolution-layers/forests/forest-type-1/status-maps/forest-type-2018?tab=download 

### Data Preprocessing

None in particular

### Quality Control

Quality assurance followed the ISO9001 standards for Quality Management and the INSPIRE data quality 
elements 

### Documents & publications

None

### Ownership

EEA

### Personal Data

no personal data are captured in this datacube

**Comment by Mohinem** [comment]
Already imported long time ago (made the request retroactively).

**Comment by Mohinem** [comment]
Time to import with original CRS

**Comment by Mohinem** [comment]
done

**Comment by KathiSchleidt** [comment]
Same as #29
