### ISSUE TITLE
Rasdaman Data Retrieval

### ISSUE THREAD

**Issue by sonjastndl** [FAIRiCUBE/data-requests#63]
This issue is related to the Wormpicker and EggDance Projects of UC3, might concern others as well.

**A whole Report on the problem statement can be found here:** 
https://nilu365.sharepoint.com/sites/Horizon2021_CUBE/_layouts/15/Doc.aspx?sourcedoc={235313bb-424e-4a1e-b1d6-92296d28fbfc}&action=edit&wd=target%28use%20cases.one%7C3de8cdde-47ec-4a25-9bf1-cd0f21c90526%2FWorm%20picker%7C1b48d8bf-5aaf-4484-9cc9-5bdf40369b87%2F%29&wdorigin=NavigationUrl

**Solution approaches that were established via Email:** 
https://github.com/FAIRiCUBE/uc3-drosophola-genetics/blob/main/projects/EggDanceSolutionApproach.txt

**Short Summary:**
No consistency in the transforming spatial geo extents when querying (retrieval of data via grid cell indices due to different undertandings of output grid domains) data on rasdaman and updates on the script by rasdaman.

Please let us continue the conversation here on GitHub @KathiSchleidt @bangph @capoony @pebau 

Also, I attached the link to the actual script I used to perform the "EggDance" with:
https://github.com/FAIRiCUBE/uc3-drosophola-genetics/blob/main/projects/EggTest.py

**Comment by robknapen** [comment]
I assume we will run into similar issues / questions when we want to sample data from multiple rasdaman data cubes (having different spatial and temporal axis) for the machine learning (model training) in our use case.

**Comment by KathiSchleidt** [comment]
@Sonja: could you add the results of the cal() calls at the end of EggDanceSolutionApproach.txt into the print string below the call?

Here the output from one of your last mails, what broke all understanding I'd thought I'd had (e.g. why does a smaller bbox provide more values?):

![image001](https://github.com/FAIRiCUBE/data-requests/assets/11915304/110c2d0d-ce64-45ba-8ec1-913034d8d376)

**Comment by sonjastndl** [comment]
@KathiSchleidt: I am not entirely sure what you mean so I did the following until now:
 
- I added the **results of multiple cal() operations** at the file, starting on line85
https://github.com/FAIRiCUBE/uc3-drosophola-genetics/blob/main/projects/EggDanceSolutionApproach.txt#L85

- I inserted the customized version of the shiftToInteger()-function, which is supposed to let you see intermediate values of the calculations, at line 99
https://github.com/FAIRiCUBE/uc3-drosophola-genetics/blob/main/projects/EggDanceSolutionApproach.txt#L99

- Execution results of the shiftToInteger_print at line 113
https://github.com/FAIRiCUBE/uc3-drosophola-genetics/blob/main/projects/EggDanceSolutionApproach.txt#L113

**Comment by KathiSchleidt** [comment]
@sonjastndl MANY THANKS! I meant the first point, but the others you added are most valuable!
Quite curious what the outcome of this thread is, if we're still confused, or if rasdaman is

**Comment by bangph** [comment]
@KathiSchleidt  @sonjastndl  @robknapen 

I'm trying to get your expectation with mapping geo coordinates (slicing / trimming) to grid indices.
This is a new formula which I think it is easier to understand for all as the grid indices is translated by only one formula with consistent results.

Can you all check to see if it makes sense?

```
Lat axis with 10 degrees resolution and it has 3 grid pixels 

geo coordinates:          [10.0                  10.9999999999999999999999999][11.0                 11.9999999999999999999999999999][12.0              12.99999999999999999999999999999]
grid pixel (zero-based):              Pixel 0                                           Pixel 1                                            Pixel 2

- Slicing:
  - Lat(10.0) -> pixel 0
  - Lat(10.1) -> pixel 0
  - Lat(10.88888) -> pixel 0
  - Lat(10.99999) -> pixel 0
  - Lat(10.99999999999999999999999) -> pixel 0
  - Lat(11.0) -> pixel 1
  - Lat(11.1) -> pixel 1
  - Lat(11.9999999) -> pixel 1
  - Lat(12.0) -> pixel 2

- Trimming:
  - Lat(10.0:10.5) -> pixel 0 : pixel 0
  - Lat(10.5:10.9) -> pixel 0 : pixel 0
  - Lat(10.99999:10.9999999) -> pixel 0 : pixel 0
  - Lat(10.99999:11.0) -> pixel 0 : pixel 1
  - Lat(11.0:11.3) -> pixel 1: pixel 1
  - Lat(11.3:11.3555) -> pixel 1: pixel 1
  - Lat(11.999999:11.999999999999) -> pixel 1 : pixel 1
  - Lat(11.99999:12.0) -> pixel 1 : pixel 2
  - Lat(11.999999999999999:12.99999999999999999999999) -> pixel 1 : pixel 2
  

The formula for rounding number for both slicing / trimming is: floor(geo_to_grid_index) = grid_index_in_integer
For example:   

- Slicing:
   - Lat(10.0) = floor(0.0) = pixel 0
   - Lat(10.1) = floor(0.1) = pixel 0
   - Lat(10.88888) = floor(0.88888) = pixel 0
   - Lat(10.9999999999999999999999) = floor(0.999999999999999999999999) = pixel 0
   - Lat(11.0) = floor(1) = pixel 1

- Trimming:
  - Lat(10.0:10.0) = floor(0.0):floor(0.0) = pixel 0 : pixel 0
  - Lat(10.1:10.1) = floor(0.1):floor(0.1) = pixel 0 : pixel 0
  - Lat(10.88888:10.88888) = floor(0.88888):floor(0.88888) = pixel 0 : pixel 0
  - Lat(10.9999999999999999999999:10.9999999999999999999999) = floor(0.999999999999999999999999) : floor(0.999999999999999999999999) = pixel 0 : pixel 0
  - Lat(11.0) = floor(1):floor(1) = pixel 1 : pixel 1

```

**Comment by robknapen** [comment]
@bangph It seems that your range indications are upper-bound inclusive? (In Python they are usually upper-bound exclusive).

**Comment by bangph** [comment]
@robknapen from my examples, it is upper-bound exclusive. For example:

```
 Lat(10.9999999999999999999999) = floor(0.999999999999999999999999) = pixel 0
```
here, it doesn't round up to pixel 1.

**Comment by robknapen** [comment]
@bangph That is indeed true when using the floor function. However I was referring to the range specifications you use in e.g. in Lat(10.0:11.0) and pixel 0 : pixel 1. Are those [10.0, 11.0> and [0, 1>, or [10.0, 11.0] and [0, 1]? (or some other interpretation?)

**Comment by bangph** [comment]
@robknapen  It is inclusive in this case:
Lat(10.0:11.0) returns [0:1]  - as you selected pixels [0, 1]

But not inclusive in this case:
Lat(10.0:10.99999999999999999999999) returns [0:0] - as you selected pixels [0, 1) - 1 is not included

**Comment by KathiSchleidt** [comment]
turning @robknapen example around, I now see the interval open at the end:

`pixel 0 = Lat(10.0:(10.0 - ε)) = [10.0, 11.0>`

A logical question - where does one formally see the value positioned? Is the value exactly at 10, or is it in the middle of the pixel, so at 10.5?

**Comment by bangph** [comment]
@KathiSchleidt  The pixel resides between interval of [10 as lower bound and 10.99999999999999999999999  as upperbound]. When you slice at any place inside this interval, you will get back the pixel.

**Comment by KathiSchleidt** [comment]
@bangph many thanks - that sounds like clear logic that I can follow! ;)
To my understanding, the code Sonja was playing with (links above, functions shiftToInteger() and cal()) was extracted from the guts of rasdaman. Has this updated code been deployed on the FAIRiCUBE rasdaman? 

@sonjastndl does the updated code now function as Bang describes it? pixel 0 = Lat(10.0:(10.0 - ε)) = [10.0, 11.0>

**Comment by bangph** [comment]
@KathiSchleidt I proposed this new simplified formula at https://github.com/FAIRiCUBE/data-requests/issues/63#issuecomment-1720898268 just for verifying with all of you first. After that @pebau needs to agree before it can be changed in petascope and then petascope on Fairicube VM can have the better and easier understanding formula.

**Comment by KathiSchleidt** [comment]
@pebau when can we expect such saner query responses within the FAIRiCUBE rasdaman instance?

**Comment by pebau** [comment]
@sonjastndl can you please confirm that Bang's formula works with you? Once OKed by you we can provide you with a working solution.

**Comment by KathiSchleidt** [comment]
@pebau while I appreciate the old German phrase "probieren geht über studieren", for SW like this, I would like a clear specification of what the formula does, what results finally get retrieved. After all the problems we've had with this, I'd really appreciate:
- A textual description of the expected behavior
- The code that implements this

I know I should be able to provide this here, but my brain is still pretty slow after my hospital stay, sure you or @bangph can easily provide in a saner form than I currently could

**Comment by pebau** [comment]
@sonjastndl any confirmation/disagreement already available? Then we can continue supporting you right away.

**Comment by KathiSchleidt** [comment]
@pebau any answers to the request for a clear description?

**Comment by sonjastndl** [comment]
@bangph Regarding your formular for slicing and trimming delivering grid indices, I can agree it would make a lot of sense for it to be that way for now, but since this is so far just a concept and I don't have a lot of backround information on how this will be implemented, for me it is hard to verify the correctness of all of it @pebau.

I can only agree with @KathiSchleidt that a textual description will ease the mental processing of the formula as well as some information where and how in the code this new formula can be implemented. In my opinion it would be useful to declare what actual changes in the results might appear and what is to be expected when implementing changes.

**Comment by KathiSchleidt** [comment]
@pebau I've now accessed the [WCS spec](https://portal.ogc.org/files/09-110r4), gone through the relevant sections. In this process, I've identified an inconsistency in the specification that may explain the erroneous behavior displayed by rasdaman. While Req 38 clearly specifies the desired behavior, the following Note is in stark contradiction to this requirement. However, as only Reqs are normative in ISO standard, Notes only informative, I believe we can focus on the specification in Req 38.

**Requirement 38 /req/core/getCoverage-response-trimming:**
`The response to a successful GetCoverage request on coverage identifier id of admissible type containing no slicing and exactly one trimming operation with dimension name dname, lower bound parameter evaluating to low, and upper bound parameter evaluating to high shall be a coverage identical to c, but containing all points of c with location inside B, and no other points.
`

In addition, the definition of B is relevant:
`B be an envelope equal to the domain of c, except that in dimension dname the extent is` **given by the closed interval** `[low,high];`
**Bold** _highlighting added_

Taking into account the definitions above, B defined by the closed interval [low,high], working on the assumption of a trivialized grid:
- Origin: 0,0
- Resolution: 1

![grafik](https://github.com/FAIRiCUBE/data-requests/assets/11915304/474f0b59-9b35-4c68-8a73-606fb3e2b08d)

We would expect the following behavior:
0 < low <=1; 1 <= high <2  	--> returns 1 value from position 1
low = 1; high = 1		--> returns 1 value from position 1
low = 0; 1 <= high <2  		--> returns 2 values, position 0 & 1
0 < low <=1; high = 2  		--> returns 2 values, position 1 & 2
low = 0; high = 2		--> returns 4 values, positions 1, 2 & 3

For more detail, please see [Coverage Subsetting Issue.docx](https://github.com/FAIRiCUBE/data-requests/blob/main/encoding-examples/Coverage%20Subsetting%20Issue.docx)

**Comment by robknapen** [comment]
I find the statement ‘location within B’ a bit ambiguous, does that include the bounds of the envelop or not? Usually spatially within means completely inside, so excluding points on the exterior boundaries.

**Comment by KathiSchleidt** [comment]
That's another interpretation, but based on the definition of B as the closed interval, would be surprised if this is not open. Also - we're not comparing to polygons, only to points. With B as the closed interval, I'd assume a point at low or high to still be contained.

However, that would lead to us getting less data, not more!

**Comment by bangph** [comment]
@sonjastndl For the output of today meeting, here is the python script which based on my formula at https://github.com/FAIRiCUBE/data-requests/issues/63#issuecomment-1720898268

You can create a sample TIFF file which matches with the input geo extents of Lat, Long axes and their geo resolutions like in the script below, then import it to petascope.

Then, with the outputs of script, you will have a pair of subsets, e.g. Lat:"CRS:1"(0:0) and Long:"CRS:1"(0:0) which you can add to your python script to generate a WCPS query like below

```
for $c in (test_coverage)
return encode(
$c[ Lat:"CRS:1"(0:0), Long:"CRS:1"(0:0) ], "tiff") // Lat:"CRS:1"(0:0), Long:"CRS:1"(0:0)  from outputs of my script depending on your input geo extents
```

and you check the output which is a tiff file to see if it makes sense.

Here is the full python script.

```
import os
import math

# geo extent in EPSG:4326
xmin = 0
xmax = 180
ymin = 0
ymax = 90

# geo resolution of Long (X) axis
xres = 1

# geo resolution of Lat (Y) axis
# NOTE: Y axis (negative resolution), grid origin starts from max geo bound
# (e.g. Lat axis, then pixel 0th is at 90 degree and pixel 89th at 0 degree with yres = -1)
yres = -1

total_number_of_grid_pixels_X = int((xmax - xmin) / xres)
total_number_of_grid_pixels_Y = int((ymax - ymin) / abs(yres))


print("Total number of grid pixels in axis Long(X): {} - with rasdaman grid domains: [0:{}]".format(total_number_of_grid_pixels_X, total_number_of_grid_pixels_X - 1))
print("Total number of grid pixels in axis Lat(Y): {} - with rasdaman grid domains: [0:{}]".format(total_number_of_grid_pixels_Y, total_number_of_grid_pixels_Y - 1))
print("")


def get_grid_indices_for_axis_X(geo_lower_bound, geo_upper_bound):       
    print("geo_lower_bound_X: {}, geo_upper_bound_X: {}".format(geo_lower_bound, geo_upper_bound))
    lower_grid_index = math.floor( (geo_lower_bound - xmin) / xres )
    upper_grid_index = math.floor( (geo_upper_bound - xmin) / xres )
    
    if geo_upper_bound == xmax:
        upper_grid_index = upper_grid_index - 1       
    
    return "Long:\"CRS:1\"" + "({}:{}) \n".format(lower_grid_index, upper_grid_index)
    
def get_grid_indices_for_axis_Y(geo_lower_bound, geo_upper_bound):
    print("geo_lower_bound_Y: {}, geo_upper_bound_Y: {}".format(geo_lower_bound, geo_upper_bound))
    lower_grid_index = math.floor( (geo_upper_bound - ymax) / yres )
    upper_grid_index = math.floor( (geo_lower_bound - ymax) / yres )
    
    if geo_lower_bound == ymin:
        upper_grid_index = upper_grid_index - 1   
 
    
    return "Lat:\"CRS:1\"" +  "({}:{}) \n".format(lower_grid_index, upper_grid_index)
    

### Get grid indices for trimmings on axis X, slicing = trimming(same_bound, same_bound)

print("Getting grid indices for axis X...\n")


grid_indices_axis_X = get_grid_indices_for_axis_X(0.5, 0.6)
print(grid_indices_axis_X)

grid_indices_axis_X = get_grid_indices_for_axis_X(0.5, 1.0)
print(grid_indices_axis_X)

grid_indices_axis_X = get_grid_indices_for_axis_X(0.5, 1.25)
print(grid_indices_axis_X)

grid_indices_axis_X = get_grid_indices_for_axis_X(0.5, 1.5)
print(grid_indices_axis_X)

grid_indices_axis_X = get_grid_indices_for_axis_X(0.5, 1.75)
print(grid_indices_axis_X)

grid_indices_axis_X = get_grid_indices_for_axis_X(0.5, 1.99999)
print(grid_indices_axis_X)

grid_indices_axis_X = get_grid_indices_for_axis_X(0.5, 2.0)
print(grid_indices_axis_X)


print("-----------------------------\n")

### Get grid indices for trimmings on axis Y, slicing = trimming(same_bound, same_bound)

# NOTE: Y axis (negative resolution), grid origin starts from max geo bound
# (e.g. Lat axis, then pixel 0th is at 90 degree and pixel 89th at 0 degree with yres = -1)

print("Getting grid indices for axis Y...\n")

grid_indices_axis_Y = get_grid_indices_for_axis_Y(89.5, 89.6)
print(grid_indices_axis_Y)

grid_indices_axis_Y = get_grid_indices_for_axis_Y(89.0, 89.5)
print(grid_indices_axis_Y)

grid_indices_axis_Y = get_grid_indices_for_axis_Y(88.5, 89.5)
print(grid_indices_axis_Y)

grid_indices_axis_Y = get_grid_indices_for_axis_Y(88.0, 89.5)
print(grid_indices_axis_Y)

grid_indices_axis_Y = get_grid_indices_for_axis_Y(87.8, 89.5)
print(grid_indices_axis_Y)

grid_indices_axis_Y = get_grid_indices_for_axis_Y(87.0000001, 89.5)
print(grid_indices_axis_Y)

grid_indices_axis_Y = get_grid_indices_for_axis_Y(86.99999, 89.5)
print(grid_indices_axis_Y)
```

**Comment by sonjastndl** [comment]
Hi @bangph 

I already did a **spot check** on your code, on some real layers available at fairicube.rasdaman, with adjusted axis naming (X and Y instead of Lat and Long) when necessary and output format text/csv, since that is the desired output for the Drosophila Landscape Genomics Pipeline . I retrieve one value, as desired :+1: 
I did not test it for other output formats so far...the upcoming days I will try to adjust it in the wormpicker script and I will run it as a whole, including the different timestamps, to see if that works as fine as the check now.

**Comment by KathiSchleidt** [comment]
What's the conclusion of this activity? My current understanding is that we must bypass the use of correct CRS, calculate the grid index for the requested cell. Is this the final solution, or a temporary workaround?

**Comment by sonjastndl** [comment]
> What's the conclusion of this activity? My current understanding is that we must bypass the use of correct CRS, calculate the grid index for the requested cell. Is this the final solution, or a temporary workaround?

I understood it as a temporary workaround, but the correct CRS is still required to calculate grid indices

**Comment by KathiSchleidt** [comment]
@bangph in the minutes of the WormPicker Telcon from October 5th, there are multiple mentions of GDAL having the same issue that rasdaman has with coordinate transformation. Does this mean that rasdaman utilizes GDAL for this purpose?

Also - what's the outlook on a solution for this issue?

**Comment by bangph** [comment]
@KathiSchleidt 

>  in the minutes of the WormPicker Telcon from October 5th, there are multiple mentions of GDAL having the same issue that rasdaman has with coordinate transformation. Does this mean that rasdaman utilizes GDAL for this purpose?

It means rasdaman will try to return a consistent result not like with gdal_translate.

> Also - what's the outlook on a solution for this issue?

As mentioned multiple times by Peter, this is not a straightforward issue and it will take longer time to evaluate formula.

**Comment by sonjastndl** [comment]
@KathiSchleidt I will continue here instead of creating a new issue. 

@bangph @pebau For the sake of documentation we need a common understanding of the findings so far and the outlook for the future of this EggDance/grid-indexing-issue.

My understanding was the following:

**START**
When querying rasdaman with point data before, one did not retrieve consistent results in some cases (EggDance Problem Statement). The finding was that this was/is the problem: There is a problem in how Petascope (https://doc.rasdaman.org/05_geo-services-guide.html) "translates input geo-subsets from WCS GetCoverage request to grid indices (zero-based index) to query from imported rasdaman collection".
Since changing this is touching very deep structures of rasdaman and this is takes time, we were provided with a code that can be implemented in the UseCase Wormpicker Code to work around this issue and have some results we can work with in the meantime. We  (me, @bangph and @pebau) had a meeting via whereby(rasdaman) and bang explained a framework code that calculates grid indices to use as query input instead of letting petascope calculate grid indices based on input coordinates, and the problem was due to **gdal.**
The code that was provided and explained in this meeting indeed can be implemented in the Wormpicker and delivers results that are familiar and expected, however I cannot verify all cases that I am not familiar with, so an absolute confirmation of correctness is not possible.
Since this is a major issue, this will be worked on and fixed, in the meantime the workaround allows further working on the UC. 
**END**


Please let me know if I forgto something.
I would be very thankful to know if everybody has the same understanding on that topic, since the development of this will be documented in the report.

**Comment by pebau** [comment]
the agreed status was that the solution provided works, so NHM is not restricted in their work in any way currently. Additionally, our internal discussion has revealed that the  method used makes sense.
