### ISSUE TITLE
Resolvable CRS

### ISSUE THREAD

**Issue by KathiSchleidt** [FAIRiCUBE/data-requests#66]
When data is provided by rasdaman, the URLs für these are unfortunately delivered addressing localhost on port 8080, example:

- http://localhost:8080/rasdaman/def/crs/EPSG/0/4326

I know that rasdaman can also return resolvable URLs, would appreciate it if the FAIRiCUBE instance was configured accordingly.

**Comment by pebau** [comment]
@bangph , can you have a look?

**Comment by bangph** [comment]
@KathiSchleidt next time, you could provide the URL which you saw the issue or better an image of it. That helps to understand the issue better.

Anyway, I configured FAIRICUBE in petascope.properties so result of WCS DescribeCoverage will return resolvable CRS URLs instead of localhost.

**Comment by KathiSchleidt** [comment]
@bangph sorry for not providing the URL, assumed that https://fairicube.rasdaman.com/rasdaman/ows was clear!
Many thanks for reconfiguring - URLs at https://crs.rasdaman.com/def/crs/ are resolving nicely!

PS: Please don't close issues until you've had confirmation from the requestor, we've had too many issues closed by rasdaman/CU, despite the core issue not being resolved. Please check the [Good Practices](https://github.com/FAIRiCUBE/FAIRiCUBE-Hub-issue-tracker#fairicube-github-best-practices) we've set up for FAIRiCUBE on this due to such issues.
