### ISSUE TITLE
Open Street Map (OSM)

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#68]

**Comment by Mohinem** [comment]
This is a vector dataset - we need to decide how to convert to raster.

**Comment by KathiSchleidt** [comment]
@Mohinem a general comment - while you created many issues on data requests, you neglected to assign responsibles to these issues. I've now gone through all the issues and assigned the relevant project partners, but would really appreciate it if you could do such basic housekeeping on your own

**Comment by robknapen** [comment]
We won't need an ingested OSM for our use case.

**Comment by pebau** [comment]
ok, so closing.
