### ISSUE TITLE
Essential Biodiversity variables (EBV)

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#72]

**Comment by Mohinem** [comment]
I found a wikipedia page which says that Essential Biodiversity Variables are a set of parameters-
https://en.wikipedia.org/wiki/Essential_Biodiversity_Variables
I also found a website-
https://portal.geobon.org/home
The datasets are small in number and cleanly arranged.
I want someone to see and decide which datasets are required to be ingested, and ALSO the temporal resolution (1 day ? 1 month ? 1 year ?), and any other comments.

**Comment by pebau** [comment]
please file a [standard data-request](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data) providing all info agreed (via issue or Web GUI, whatever). Closing this issue therefore.
