### ISSUE TITLE
HR VPP (NDVI, PPI, FAPAR, LAI)

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#73]

**Comment by Mohinem** [comment]
There are multiple CLMS datasets at - 

https://land.copernicus.eu/en/products/vegetation

I need someone to list me ALL the datasets that are needed to be ingested. Can anyone help me here ?

**Comment by KathiSchleidt** [comment]
related to #85

**Comment by pebau** [comment]
for any data needed, please file a [standard data-request](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data) for each item. Closing this issue, therefore.
