### ISSUE TITLE
Statistical data on species

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#74]

**Comment by Mohinem** [comment]
https://opendata.cbs.nl/#/CBS/en/

There is this website, but I don't know what 'statistical data on species' means. Can anyone help me find the datasets I need to import ?

**Comment by vittekm** [comment]
These are non-spatial but statistical data for species. Link to data is: https://www.clo.nl/onderwerpen/biodiversiteit
We made selection of indicators for which tabular data can be downloded from: https://filesender.surf.nl/?s=download&token=9d13085b-2d67-401d-b756-d25d050a2e24

**Comment by KathiSchleidt** [comment]
@vittekm if these data are non-spatial, how do you expect them to be imported to a geospatial datacube?
My impression is that this is tabular data that Rob will utilize in his ML algorithms, but nothing that can/will be stored in a datacube - can you confirm?

**Comment by vittekm** [comment]
@KathiSchleidt it's true that these non-spatial data can't be directly use in geospatial datacube. This data we can however link to spatial layers. We could either do it before importing or possibly then on rasdaman server.

**Comment by KathiSchleidt** [comment]
@vittekm based on your description, it sounds like quite a bit of work must be done before this data can be utilized anywhere.
How do you foresee linking this data to spatial layers? Which spatial layers?

**Comment by robknapen** [comment]
The statistical (tabular) data usually does have some implicit spatial dimension though, i.e. it concerns data about The Netherlands, sometimes divided into administrative regions (e.g. provinces, municipalities, zip codes). So it can still be a data cube with a spatial dimension. However, it might not fit well with the gridded/coverage type of data cubes we apply and another way to makes this data FAIR could be needed (a relational database, or csv files on shared storage?).

**Comment by KathiSchleidt** [comment]
@Mohinem what's the outlook for integration of data with non-geospatial dimensions in other formats? We'll be needing this soon in order to support the Occurrence Cubes where the data will be provided as a CSV with one column referencing the grid cell.

On this dataset, from what I've seen, the spatial dimension is reduced to the country, while you'd need a dimension for the year as well as the species. Do you have tool for converting such CSV files to cubes?

**Comment by pebau** [comment]
discussion reveals that information is insufficient for ingestion. Closing this issue, therefore, feel free to create anew one following the [standard procedure](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data) with all info agreed.
