### ISSUE TITLE
Agricultural nature management (ANB) 

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#75]

**Comment by Mohinem** [comment]
According to the inventory, this link takes me to a Dutch website-
https://www.rvo.nl/onderwerpen/glb/anlb/agrarisch-natuurbeheer

I believe this is related to WER. I would like someone to find me a way to download datasets from here.

**Comment by vittekm** [comment]
This is relevant but restricted dataset which we have available at WENR. We can't share it for the time being and we'lll try to find a way in what form it could be possible ingest it.

**Comment by pebau** [comment]
ok, so closing this.
