### ISSUE TITLE
Agrodatacube

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#77]

**Comment by Mohinem** [comment]
This is the agro-datacube link-

https://agrodatacube.wur.nl

To download data, I need a token (which I have), and there is a limit to number of requests (25k) and the area downloaded (1000000 ha). I have the following questions-

1. Is the area sufficient to cover whole of the Netherlands ?
2. The other factors - bounding box (of the region ingested), resolution, time axes etc. They are in the inventory.

**Comment by robknapen** [comment]
We can temporarily provide an unlimited access token for AgroDataCube. However, since AgroDataCube mostly provides (vector) crop parcels for multiple years with several attributes, I think a selection has to be made first. There is an overlap with the request for the BRP data as well.

@vittekm Can you filter this down a bit and decide what source to use for the crop parcel information?

**Comment by KathiSchleidt** [comment]
Have we agreed on how these vector sources are to be transformed to raster?

**Comment by vittekm** [comment]
We can use BRP for parcel information and also the rest of data available in Agrodatacube could be taken from individual sources I think. So for now, I would not include Agrodatacube in the ingestion.

**Comment by robknapen** [comment]
@vittekm Are the alternate data sources already on the ingestion list? Or otherwise can you please introduce them and then close this issue.

**Comment by vittekm** [comment]
After some internal discussions at WENR we decided that it will be more consistent to ingest multiple datasets (including BRP) through Agrodatacube. Also it would be more efficient when we extract data from Agrodatacube (rather then explaining how to access it and download) and then provide it through download link for ingestion.

**Comment by pebau** [comment]
good discussion! So obviously a next step would be to obtain pre-selected and pre-downloaded datasets for ingestion. Once this is the case, please create a [standard request](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data).
