### ISSUE TITLE
RS derived signals, markers and indices

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#78]

**Comment by Mohinem** [comment]
Remote Sensing derived - likely Sentinel 1 and 2

This is the description in the inventory sheet. It doesn't tell me anything. Please help. I need the dataset, and a description of the information required for ingestion.

**Comment by KathiSchleidt** [comment]
These datasets are probably already available via ds.rasdaman.com. However, we still don't have access.

In the Inventory Sheet, they're listed under UC2, here under UC3. Assigning participants from both.

**Comment by robknapen** [comment]
If I recall correctly this request is related to the calculation of indicator values (KPIs) for agricultural parcels, as part of UC2. Starting from remote sensing signals there are ‘markers’ calculated for each crop field. E.g. if the field has been ‘green’ al year long, or an estimated crop harvest day. These markers are then helpful in calculation certain indices.

It is a compound request that needs to be broken down into actual data needed and then checked for what is already available and what has to be added, and potentially which calculations need to be made.

**Comment by KathiSchleidt** [comment]
@Mohinem any outlook when we'll be permitted to access the data available via ds.rasdaman.com? It's been linked to the FAIRiCUBE rasdaman for a few weeks now, but the credentials provided to FAIRiCUBE partners don't allow for access.

**Comment by pebau** [comment]
feel free to file a [standard data-request](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data) on concrete datasets requested; closing for now.
