### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#80]

**Comment by Mohinem** [comment]
This is the website-

knmi.nl

it's in Dutch.

Please tell me a way to download the datasets. Also fill out the inventory sheet.

**Comment by pebau** [comment]
> Please tell me a way to download the datasets. Also fill out the inventory sheet.

...so feel free to file an issue the [following standard procedure](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data). Closing here.
