### ISSUE TITLE
Copernicus DEM

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#81]

**Comment by robknapen** [comment]
Are there any specific questions about making this digital elevation data available? I would suggest using the EEA-10 data with European coverage. Perhaps it is already available in rasdaman?

**Comment by robknapen** [comment]
@Mohinem There already seems to be an EU-DEM dataset in rasdaman (ds.rasdaman.com:7000:EU_DEM), but my account does not have sufficient permissions to access it.

**Comment by pebau** [comment]
closing this issue as it is not a [standard data-request issue](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data). Feel free to [file a data-request issue](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data) at any time.
