### ISSUE TITLE
EU Demography

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#84]

**Comment by Mohinem** [comment]
Here's a link to the website containing the dataset-

https://ec.europa.eu/eurostat/web/population-demography/demography-population-stock-balance/database

There are multiple datasets. Please earmark the ones for ingestion.

**Comment by KathiSchleidt** [comment]
@Mohinem why are you now looking at the vector datasets at eurostat? The request was for the raster datasets available from https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/population-distribution-demography/geostat

eurostat provides demography for 4 years on the LAEA grid at a 1km resolution. 
- For the years 2018 & 2021 you find a TIF file in the zip, should be fairly easy to import
- For the years 2006 & 2011, a CSV file is provided with reference to the LAEA grid cell. As I'm pretty sure that you cannot easily import this format into rasdaman, we should see if the UC really need this, or if 2018 & 2021 suffice

@capoony would the 2018 demography be enough for your purposes, or would you also need the 2011 dataset?

**Comment by sonjastndl** [comment]
@KathiSchleidt We have data ranging from 2010 to 2021 so we would be happy to have the 2011 dataset as well.

**Comment by KathiSchleidt** [comment]
@sonjastndl @Mohinem I'd still recommend starting with the 2018 or 2021 dataset, as this is a standard format (TIF)

When can we expect the CSV to be imported?

**Comment by sonjastndl** [comment]
added this to Inventory_V2.xlsx @pebau

**Comment by sonjastndl** [comment]
@Mohinem 
What is the status here?
What information is needed from the UseCase(s) for this to be ingested?

**Comment by pebau** [comment]
As this data request is incomplete and not following the [standard procedure](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data) (which obviously is a reason for the confusion here) I close it. Feel free to create a [standard, complete data request issue](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data) at any time or - preferably - call for a telco to allow clarification of all necessary details.
