### ISSUE TITLE
Genomic data of Drosophila

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#86]

**Comment by sonjastndl** [comment]
Very similar to this answer: https://github.com/FAIRiCUBE/data-requests/issues/87#issuecomment-1807641548
I guess the way genomic data will be ingested comes down to the way we talked about in Bremen.

**Comment by sonjastndl** [comment]
Added this feedback to Inventory_V2.xlsx @pebau

**Comment by pebau** [comment]
I have added a [section for the modeling documentation](https://github.com/FAIRiCUBE/data-requests/blob/main/README.md#drosophila) - please feel free to feed with details.

**Comment by pebau** [comment]
If you feel all information is collected please create a data-request issue. Also,  please check whether 
[my understanding](https://github.com/FAIRiCUBE/data-requests/blob/main/README.md#drosophila-use-case-occurrence-cube) is correct.

**Comment by sonjastndl** [comment]
Hi @pebau,

I have answered to [your understaning ](https://github.com/FAIRiCUBE/data-requests/blob/main/README.md#drosophila-use-case-occurrence-cube) in the [related issue](https://github.com/FAIRiCUBE/data-requests/issues/87#issuecomment-1857413820) since, as I've mentioned, I suspect there is a severe mixup in topics.

**Comment by sonjastndl** [comment]
Additionally, this would be of course nice to have ingested, yet our primary interests lie in the ingestion of basic datasets (earth observation data) to encourage downstream analysis and allow progress in the development of our wormpicker tool. 

@KathiSchleidt

**Comment by pebau** [comment]
@sonjastndl also in this issue: thank you for your input, this is essential.

You seem doubtful about whether this cube is necessary actually - please clarify, and if the decision is that it should be 
established then the next step is to create the data-request issue, allowing us to start creating the cube.

**Comment by sonjastndl** [comment]
Sorry for this misleading formulation of words. This cube is necessary, since it is an essential part of our Use Case goal. However, without earth observation data conducingt analysis on the interaction between EOs and drosophila genomic data is difficult, additionally ingesting EO data seems to inherit faster progress and expertise.

**Comment by pebau** [comment]
understood, and I did not mean to restrict in any way - please feel free to create a request for additional datasets, too.

**Comment by KathiSchleidt** [comment]
@sonjastndl @pebau agreed. While the cubification of the genomic data currently being stored in VCF format would be a great attainment for FAIRiCUBE, it is currently of a lower priority. Reasoning is that 
- If we cannot reach this level, it is still possible to perform the core UC3 activities just with the WormPicker. 
- At the same time, if we cannot get the base data foreseen for the WormPicker available in a useable manner, UC3 will fail, shedding a bad light on all partners involved

In German we say "zuerst die Pflicht, dann die Kür" (first the necessary, then the nice-to-have)

**Comment by pebau** [comment]
on a side note, the wormpicker support has been provided ~3 months back, but this is not the topic of this issue.

As no particular action is associated with this issue any more, closing it. Feel free to file a regular data-request issue following the [standard procedure](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data) at any time.
