### ISSUE TITLE
Distribution data of Drosophila

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#87]

**Comment by sonjastndl** [comment]
Maybe we should have a closer look aon what that issue means. Is this just to keep track on what is still to ingest or is any further information from us required? 
The distribution in the ways of (Population 1, Lat: ... Lon:...) is stored in the VCF file we provided, if that is what is asked for.

**Comment by KathiSchleidt** [comment]
Looking at the [data source](https://www.taxodros.uzh.ch/search/dist_sreg.php), this looks like point data on Drosophila distribution, could be rasterized to an Occurrence Cube. Nothing that can be directly imported

**Comment by sonjastndl** [comment]
Yes if there is a nice way to extract the point data from the "chosen" list I would think so

**Comment by KathiSchleidt** [comment]
related to #71 
once we have the Occurrence Cube Pipeline implemented by B-Cubed, we can continue on this dataset

**Comment by pebau** [comment]
If you feel all information is collected please create a data-request issue. Also,  please check whether 
[my understanding](https://github.com/FAIRiCUBE/data-requests/blob/main/README.md#drosophila-use-case-occurrence-cube) is correct.

**Comment by sonjastndl** [comment]
@pebau I am little bit confused right now, so maybe if you could provide me a short summary of the information collected, so I can give my estimation on that? 
Maybe this topic needs a little bit more discussion since the data source that is metnioned above is basically a listing of occurences and no gridded or rasterized data if I understood correctly ...

**Comment by sonjastndl** [comment]
When I read [your understanding ](https://github.com/FAIRiCUBE/data-requests/blob/main/README.md#drosophila-use-case-occurrence-cube) of this, I have the impression things get mixed up. Genomic data of Drosophila and Distribution Data of Drosophila are differently handled.

1) The genomic data is a specific dataset, that inherits information about sampling (which can be also used as occurence data of course) that is linked to the genetic data. Datacube Structure: This data is in the form of the VCF and has a samples spanning multiple years (not only 2018) - The domain dimensions should be specified already according to our Bremen meeting. 

I guess the proposed datacube structure is deviated from GBIF? The occurence data includes GBIF data and data from [Taxodros ](https://www.taxodros.uzh.ch/search/dist_sreg.php). This data can be interwoven in UseCase5 @heimor. Anyhow I am not certain if the time dimension value 2018 is underestimated or supposed to demonstrate formatting and resolution.

**Comment by pebau** [comment]
@sonjastndl thanks for providing these bits, that was the clarification I had hoped for. Have reflected that in the description now. 

So the next step is to create the data-request issue, then we can start creating the cube.

**Comment by pebau** [comment]
> related to #71 once we have the Occurrence Cube Pipeline implemented by B-Cubed, we can continue on this dataset

...hence, closing this issue.
