### ISSUE TITLE
[Not a Data Request]: Assignment to relevant dataset per UC partner

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#88]
I have gone through the remaining datasets earmarked for ingestion with Rasdaman, and they are a lot.

There is a new inventory sheet [(inventory V2)](https://nilu365.sharepoint.com/:x:/r/sites/Horizon2021_CUBE/Shared%20Documents/WP2%20-%20use/DataLayerInventory/[Inventory_V2.xlsx](https://nilu365.sharepoint.com/:x:/r/sites/Horizon2021_CUBE/Shared%20Documents/WP2%20-%20use/DataLayerInventory/Inventory_V2.xlsx?d=w8c509b9628d446448d1b08c407c349de&csf=1&web=1&e=NhObre)?d=w8c509b9628d446448d1b08c407c349de&csf=1&web=1&e=NhObre) to keep track of information related to ingestion.

I need your help for the following-

1. Please confirm if you can EDIT the inventory.

2. I assigned one of the ingestion issues to Rob, but that wasn't helpful as it wasn't very relevant. So to avoid this, I have created this issue. 

There are multiple datasets relevant to different UC owners (by WER and NHM). I would like you to assign yourself to dataset relevant to your use case. There is a small table to keep track of the number on the first column on the ingestion sheet and the issue number on the GitHub (with the link to the issue).

- Climate extremes indices and heat stress indicators - No. 27 - [70](https://github.com/FAIRiCUBE/data-requests/issues/70)
- Copernicus DEM - No. 28 - [81](https://github.com/FAIRiCUBE/data-requests/issues/81)
- Global Biodiversity Information Facility (GBIF) - No. 31 - [71](https://github.com/FAIRiCUBE/data-requests/issues/71)
- Essential Biodiversity Variables (EBV) - No. 32 - [72](https://github.com/FAIRiCUBE/data-requests/issues/72)
- HR VPP (NDVI, PPI, FAPAR, LAI) - No. 33 - [73](https://github.com/FAIRiCUBE/data-requests/issues/73)
- Statistical data on species - No. 34 - [74](https://github.com/FAIRiCUBE/data-requests/issues/74)
- Local research outcomes - No. 35 [82](https://github.com/FAIRiCUBE/data-requests/issues/82)
- Crop Parcel Registration - No. 36 - [20](https://github.com/FAIRiCUBE/data-requests/issues/20)
- Agricultural nature management (ANB) - No. 37 (75)[https://github.com/FAIRiCUBE/data-requests/issues/75]
- KPIs on agricultural land management - No. 38 - [76](https://github.com/FAIRiCUBE/data-requests/issues/76)
- Agrodatacube - No. 39 - [77](https://github.com/FAIRiCUBE/data-requests/issues/77)
- RS derived signals, markers and indices - No. 42 - [78](https://github.com/FAIRiCUBE/data-requests/issues/78)
- Actual height database (AHN) - No. 43 - [79](https://github.com/FAIRiCUBE/data-requests/issues/79)
- Weather - No. 46 - [80](https://github.com/FAIRiCUBE/data-requests/issues/80)
- Global Pesticide Grids (PEST-CHEMGRIDS), v1.01 - No. 47 - [83](https://github.com/FAIRiCUBE/data-requests/issues/83)
- EU Demography - No. 48 - [84](https://github.com/FAIRiCUBE/data-requests/issues/84)
- Vegetation Indexes (TBD) - No. 49 - [85](https://github.com/FAIRiCUBE/data-requests/issues/85)
- Genomic data of Drosophila - No. 50 - [86](https://github.com/FAIRiCUBE/data-requests/issues/86)
- Distribution data of Drosophilia - No. 51 - [87](https://github.com/FAIRiCUBE/data-requests/issues/87)

5. I have left comments on most of the issues on GitHub. If possible, please answer them.

This will help me proceed with the datasets that I have seen, but not touched.

**Comment by Mohinem** [comment]
That really helps! Thanks.

**Comment by robknapen** [comment]
@Mohinem And the Drosophila datasets (no 50 and 51) are for NHM. We (WEnR) should not mess with that :)

**Comment by capoony** [comment]
Dear @Mohinem, thanks a lot! Please also include @sonjastndl since she is primarily working on the datasets

**Comment by sonjastndl** [comment]
Hi @Mohinem!
Concerning your first point (inventory sheet), unfortunately I cannot access it...

I assigned myself to the corresponding datasets and commented some! :)

**Comment by vittekm** [comment]
Hi @Mohinem,
I could access inventory by following path: WP2 - use/DataLayerInventory/Inventory_V2.xlsx on Teams site but it seems that link you aded above is broken.
Marian

**Comment by sonjastndl** [comment]
Yes, the path @vittekm provided seems to work, just the link is broken.

**Comment by pebau** [comment]
as the Fall 2023 user meeting has revealed that all datasets required by the use cases are currently available, and as we are in transitino from the inventory sheet to the Web GUI, we can close this issue.
